### ISSUE TITLE
keepalived reacts badly to temporary loss of IPv4 address

### ISSUE THREAD

**Issue by sleinen** [switch-ch/switchdrive-ansible#1]
SWITCHdrive runs on SWITCHengines, an OpenStack-based IaaS platform.  This infrastructure uses DHCP to assign IPv4 and IPv6 addresses to SWITCHdrive servers, which are OpenStack _instances_.  Each (virtual) OpenStack network has two DHCP servers for redundancy and load sharing.  These servers are implemented by `dnsmasq` processes, which can also serve DNS requests from instances.  The DHCP servers do not maintain any dynamic address pools; the mappings from MAC to IP addresses are fixed by configuration files that are produced by OpenStack's "neutron-dhcp-agent" based on the addresses that the "Nova" compute service assigns to instance ports.

From time to time, the neutron-dhcp-agent needs to be restarted for operational reasons such as configuration changes, upgrades, or maintenance on the underlying servers.  Restarting a neutron-dhcp-agent also causes the restart of all DHCP servers.

When an OpenStack instance is booted, it discovers each of its addresses and "leases" it from one of the DHCP servers.  Then it will periodically try to revalidate each address with that DHCP server: The instance sends a DHCPREQUEST message for its current address to the server, and the server responds with a DHCPACK.

When a DHCP server is restarted, this will lead to a failure to do so: Because the DHCP server lost information about its current leases, it will respond with a DHCPNAK.  (This behavior was reported as OpenStack bug [#1345947](https://bugs.launchpad.net/neutron/+bug/1345947).  An attempt to fix this caused the even worse bug [#1457900](https://bugs.launchpad.net/neutron/+bug/1457900), and thus had to be reverted.)  The instance will then "discover" a new address, just like when it booted.  Because all addresses are statically mapped, it will receive the same address as before, though possibly from a different DHCP server.  The effect is that the address is lost for a short time before it is reconfigured.

The current configuration of `keepalived` handles this situation very ungracefully: On the primary load balancer with regular ("unicast") IPv4 address 10.0.23.51, the temporary loss of that address leads to permanent loss of the Virtual IP (vip) 10.0.23.11.  Neither does the secondary load balancer (with unicast IPv4 address 10.0.23.52 and vip 10.0.23.12) take over vip 10.0.23.11, nor is the vip restored on lb1 after 10.0.23.51 comes back.

It is possible that this bad behavior of `keepalived` is a regression that was introduced when IPv6 handling was added to its configuration, and maybe related to limitations in IPv6 support of our version of `keepalived`.  SWITCHdrive uses the standard `keepalived` version that comes with Ubuntu 16.04, namely 1:1.2.19-1ubuntu0.1.  Newer versions would be available from various PPAs, e.g. [keepalived stable](https://launchpad.net/~keepalived/+archive/ubuntu/stable) or [keepalived daily](https://launchpad.net/~keepalived/+archive/ubuntu/daily), or [Hiroaki Nakamura's PPA](https://launchpad.net/~hnakamur/+archive/ubuntu/keepalived) (1.3.7).  Of course it would also be possible to compile it from [source](http://www.keepalived.org/download.html).

**Comment by sleinen** [comment]
I was able to reproduce this in an isolated test environment: `ktest{1,2}.leinen.ch`.  When the unicast IPv4 address on `ktest1` is removed for a short time, then the vip will be dropped on `ktest1`, not provisioned on `ktest1`, and not come back on `ktest1` when the unicast IPv4 is added back.

```
$ ip -4 addr list; \
sudo ip -4 addr del 10.255.255.21/24 dev ens3; \
sleep 0.1; \
sudo ip -4 addr add 10.255.255.21/24 dev ens3; \
sleep 10; \
ip -4 addr list
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: ens3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    inet 10.255.255.21/24 scope global ens3
       valid_lft forever preferred_lft forever
    inet 10.255.255.11/24 scope global secondary ens3
       valid_lft forever preferred_lft forever
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: ens3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    inet 10.255.255.21/24 scope global ens3
       valid_lft forever preferred_lft forever
```

The vip also doesn't appear on the other host `ktest2`.

Note how the vip 10.255.255.11 has been lost for good.  It can be restored by stopping and starting `keepalived`, but it can also be restored by stopping `haproxy` and restarting it: That will cause a proper VRRP fail-over/fail-back between the `keepalived`s.

**Comment by sleinen** [comment]
I upgraded keepalived to 1.2.23 from the [keepalived stable](https://launchpad.net/~keepalived/+archive/ubuntu/stable) PPA.  This didn't help at all.

Then I upgraded to 1.3.7 from [Hiroaki Nakamura's PPA](https://launchpad.net/~hnakamur/+archive/ubuntu/keepalived).  This caused warnings and error messages during startup.  I had to change `/etc/keepalived/keepalived.conf` as follows:

Add the following section:

```
global_defs {
    script_user nobody
    enable_script_security
}
```
Globally replace `pidof` with `/usr/bin/pgrep`.  First I had replaced `pidof` with `/bin/pidof`, but that didn't work as intended.  I assume this is because keepalived ("script security"?) resolves the symlink from `/bin/pidof` to `/bin/killall5`, but `killall5` would need to know that it was called under the `pidof` name in order to work like `pidof`.

With these changes, keepalived 1.3.7 works. But it exhibits the same ungraceful behavior as the older versions when the IPv4 address is temporarily lost.

**Comment by schnidrig** [comment]
I changed the lb to used fixed ip addresses instead of dhcp.

**Comment by sleinen** [comment]
Excellent, thanks!

**Comment by peterbulmer** [comment]
A quick, but hopefully illuminating "me too".
Openstack involved
VRRP / keepalived
DHCP ip addresses
we have this configuration in maybe 10 places, have had outages in 2 of them, twice in each place.
Both the places which are proving outage-prone are IPV6 enabled, the others aren't.
=> moving to static ips.
