### ISSUE TITLE
Database goes away during long WebDAV uploads

### ISSUE THREAD

**Issue by sleinen** [switch-ch/switchdrive-ansible#7]
The following problem has been noticed with some users who presumably back up (parts of) their home NAS to SWITCHdrive via WebDAV:

The NAS sends a large file via WebDAV. The upload takes about 45 minutes. The file is stored with a suffix of `.ocTransferId<RANDOM>.part`. When the upload is finished, the ownCloud server returns a 500 error to the client (the NAS) and logs something similar to this to `/var/log/owncloud/owncloud.log` (modified for readability and privacy):

```
{
   "File" : "/var/webroot/a01/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php",
   "Code" : 0,
   "Line" : 115,
   "Trace" : "#0 /var/webroot/a01/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(116): Doctrine\\DBAL\\Driver\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))
#1 /var/webroot/a01/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(836): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'SELECT `fileid`...', Array)
#2 /var/webroot/a01/lib/private/db/connection.php(184): Doctrine\\DBAL\\Connection->executeQuery('SELECT `fileid`...', Array, Array, NULL)
#3 /var/webroot/a01/lib/private/files/cache/cache.php(128): OC\\DB\\Connection->executeQuery('SELECT `fileid`...', Array)
#4 /var/webroot/a01/lib/private/files/cache/homecache.php(75): OC\\Files\\Cache\\Cache->get('files/...')
#5 /var/webroot/a01/lib/private/files/view.php(1269): OC\\Files\\Cache\\HomeCache->get('files/...')
#6 /var/webroot/a01/lib/private/files/view.php(1322): OC\\Files\\View->getCacheEntry(Object(OCA\\Files_Trashbin\\Storage), 'files/...', '/...')
#7 /var/webroot/a01/lib/private/files/node/hookconnector.php(143): OC\\Files\\View->getFileInfo('/...')
#8 /var/webroot/a01/lib/private/files/node/hookconnector.php(77): OC\\Files\\Node\\HookConnector->getNodeForPath('/...')
#9 /var/webroot/a01/lib/private/hook.php(105): OC\\Files\\Node\\HookConnector->write(Array)
#10 /var/webroot/a01/apps/dav/lib/connector/sabre/file.php(267): OC_Hook::emit('OC_Filesystem', 'write', Array)
#11 /var/webroot/a01/apps/dav/lib/connector/sabre/file.php(163): OCA\\DAV\\Connector\\Sabre\\File->emitPreHooks(true)
#12 /var/webroot/a01/3rdparty/sabre/dav/lib/DAV/Server.php(1070): OCA\\DAV\\Connector\\Sabre\\File->put(Resource id #38)
#13 /var/webroot/a01/3rdparty/sabre/dav/lib/DAV/CorePlugin.php(511): Sabre\\DAV\\Server->updateFile('...', Resource id #38, NULL)
#14 [internal function]: Sabre\\DAV\\CorePlugin->httpPut(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))
#15 /var/webroot/a01/3rdparty/sabre/event/lib/EventEmitterTrait.php(105): call_user_func_array(Array, Array)
#16 /var/webroot/a01/3rdparty/sabre/dav/lib/DAV/Server.php(459): Sabre\\Event\\EventEmitter->emit('method:PUT', Array)
#17 /var/webroot/a01/3rdparty/sabre/dav/lib/DAV/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))
#18 /var/webroot/a01/apps/dav/appinfo/v1/webdav.php(56): Sabre\\DAV\\Server->exec()
#19 /var/webroot/a01/remote.php(145): require_once('/var/webroot/a0...')
#20 {main}",,
   "Exception" : "Doctrine\\DBAL\\Exception\\DriverException",
   "Message" : "An exception occurred while executing 'SELECT `fileid`, `storage`, `path`, `parent`, `name`, `mimetype`, `mimepart`, `size`, `mtime`,
					   `storage_mtime`, `encrypted`, `etag`, `permissions`, `checksum`
				FROM `oc_filecache` WHERE `storage` = ? AND `path_hash` = ?' with params [\"16889\", \"ea0442aa7face1e2d5f8c35f7884cd4c\"]:

SQLSTATE[HY000]: General error: 2006 MySQL server has gone away"
}
```

The `.part` file is left in place, taking up space. The NAS will reattempt to upload the same file over and over, creating new `.part` files and filling up the disk.

There are two problems here:

1. The ownCloud server doesn't handle the exception well.  In particular, it should have removed the `.part` file.
1. The ownCloud server tries to use the database connection after it has been inactive for a long time (during the WebDAV upload).  This fails because of a timeout of the connection.

The first is easy to fix, just catch exceptions around the `emitPreHooks` call after handling the upload, and remove the `.part` file, if any.  There are examples earlier and later in the code that show how this can be done.

For the second, we could try to apply the workaround that has been used in a similar case—see `reconnect-after-assemble.patch`.  The code checks whether the database connection can still be used (using a `ping()`), and if not, closes and reopens it.  Note that this would be inappropriate if there's supposed to be a database transaction around the code.  If that should turn out to be the case, another workaround would be to try keeping the connection open during the upload by `ping()`ing the connection from time to time—but too often in order to avoid overloading the DB server, and not too infrequently in order to avoid the timeout.

**Comment by kerins** [comment]
REsolved by increasing the db time out
